name: /opt/miniconda3
channels:
  - conda-forge
  - defaults
dependencies:
  - _python_abi3_support=1.0=hd8ed1ab_2
  - anaconda-anon-usage=0.7.2=py313hd6b623d_100
  - anaconda-auth=0.8.6=py313hca03da5_0
  - anaconda-cli-base=0.5.2=py313hca03da5_0
  - annotated-types=0.6.0=py313hca03da5_0
  - anyio=4.11.0=pyhcf101f3_0
  - appnope=0.1.4=pyhd8ed1ab_1
  - archspec=0.2.3=pyhd3eb1b0_0
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=25.1.0=py313hcdf3177_0
  - arrow=1.3.0=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-lru=2.0.5=pyh29332c3_0
  - attrs=25.3.0=pyh71513ae_0
  - babel=2.17.0=pyhd8ed1ab_0
  - beautifulsoup4=4.14.2=pyha770c72_0
  - blas=1.0=openblas
  - bleach=6.2.0=pyh29332c3_4
  - bleach-with-css=6.2.0=h82add2a_4
  - boltons=25.0.0=py313hca03da5_0
  - brotlicffi=1.0.9.2=py313h313beb8_1
  - bzip2=1.0.8=h80987f9_6
  - c-ares=1.34.5=h2ca31fc_0
  - ca-certificates=2025.9.9=hca03da5_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - certifi=2025.10.5=py313hca03da5_0
  - cffi=1.17.1=py313h3eb5a62_1
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.2.1=py313hca03da5_0
  - colorama=0.4.6=py313hca03da5_0
  - comm=0.2.3=pyhe01879c_0
  - conda=25.9.0=py313h8f79df9_0
  - conda-anaconda-telemetry=0.3.0=pyhd3eb1b0_1
  - conda-anaconda-tos=0.2.2=py313hca03da5_1
  - conda-content-trust=0.2.0=py313hca03da5_1
  - conda-libmamba-solver=25.4.0=pyhd3eb1b0_0
  - conda-package-handling=2.4.0=py313hca03da5_0
  - conda-package-streaming=0.12.0=py313hca03da5_0
  - cpp-expected=1.1.0=h48ca7d4_0
  - cpython=3.13.7=py313hd8ed1ab_100
  - cryptography=45.0.5=py313hace6d20_0
  - debugpy=1.8.17=py313hc37fe24_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - distro=1.9.0=py313hca03da5_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.1=h313beb8_0
  - fmt=9.1.0=h48ca7d4_1
  - fqdn=1.5.1=pyhd8ed1ab_1
  - frozendict=2.4.2=py313hca03da5_0
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=73.1=h313beb8_0
  - idna=3.7=py313hca03da5_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=6.30.1=pyh92f572d_0
  - ipython=9.6.0=pyhfa0c392_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jaraco.classes=3.4.0=py313hca03da5_0
  - jaraco.context=6.0.0=py313hca03da5_0
  - jaraco.functools=4.1.0=py313hca03da5_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - json5=0.12.1=pyhd8ed1ab_0
  - jsonpatch=1.33=py313hca03da5_1
  - jsonpointer=3.0.0=py313hca03da5_0
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jsonschema-with-format-nongpl=4.25.1=he01879c_0
  - jupyter-lsp=2.3.0=pyhcf101f3_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.17.0=pyhcf101f3_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.4.9=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.27.3=pyhd8ed1ab_1
  - keyring=25.6.0=py313hca03da5_0
  - krb5=1.21.3=h237132a_0
  - lark=1.3.0=pyhd8ed1ab_0
  - libarchive=3.7.7=h8f13d7a_0
  - libcurl=8.14.1=hcdd2897_1
  - libcxx=19.1.7=hb09ecce_3
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h1a28f6b_1
  - libffi=3.4.4=hca03da5_1
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libiconv=1.16=h80987f9_3
  - libmamba=2.0.5=h15e39b3_1
  - libmambapy=2.0.5=py313h48ca7d4_1
  - libmpdec=4.0.0=h80987f9_0
  - libnghttp2=1.57.0=h62f6fdd_0
  - libopenblas=0.3.30=hf2bb037_0
  - libsodium=1.0.20=h99b78c6_0
  - libsolv=0.7.30=h514c7bf_1
  - libssh2=1.11.1=h3e2b118_0
  - libxml2=2.13.8=h0b34f26_0
  - llvm-openmp=19.1.7=h3b2fb71_2
  - lz4-c=1.9.4=h313beb8_1
  - markdown-it-py=2.2.0=py313hca03da5_1
  - markupsafe=3.0.3=py313h7d74516_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mdurl=0.1.0=py313hca03da5_0
  - menuinst=2.3.1=py313hca03da5_0
  - mistune=3.1.4=pyhcf101f3_0
  - more-itertools=10.3.0=py313hca03da5_0
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert-core=7.16.6=pyh29332c3_0
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.5=hee39554_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - nlohmann_json=3.11.2=h313beb8_0
  - notebook=7.4.7=pyhd8ed1ab_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - numpy=2.3.3=py313h4bb6f22_0
  - numpy-base=2.3.3=py313h23175f9_0
  - openssl=3.5.4=h5503f6c_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=25.0=py313hca03da5_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.5=pyhcf101f3_0
  - pcre2=10.42=hb066dcc_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.1=pyhc872135_2
  - pkce=1.0.3=py313hca03da5_0
  - platformdirs=4.3.7=py313hca03da5_0
  - pluggy=1.5.0=py313hca03da5_0
  - prometheus_client=0.23.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.0=py313h6535dbc_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pybind11-abi=5=hd3eb1b0_0
  - pycosat=0.6.6=py313h80987f9_2
  - pycparser=2.21=pyhd3eb1b0_0
  - pydantic=2.11.7=py313hca03da5_0
  - pydantic-core=2.33.2=py313h5e3a92f_0
  - pydantic-settings=2.6.1=py313hca03da5_0
  - pygments=2.19.1=py313hca03da5_0
  - pyjwt=2.10.1=py313hca03da5_0
  - pyobjc-core=11.0=py313hb6afeec_0
  - pyobjc-framework-cocoa=11.0=py313hb6afeec_0
  - pysocks=1.7.1=py313hca03da5_0
  - python=3.13.5=h2eb94d5_100_cp313
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-dotenv=1.1.0=py313hca03da5_0
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-gil=3.13.7=h4df99d1_100
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python.app=3=py313h80987f9_2
  - python_abi=3.13=0_cp313
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=py313h7d74516_0
  - pyzmq=27.1.0=py312hd65ceae_0
  - readchar=4.0.5=py313hca03da5_0
  - readline=8.3=h0b18652_0
  - referencing=0.36.2=pyh29332c3_0
  - reproc=14.2.4=h313beb8_2
  - reproc-cpp=14.2.4=h313beb8_2
  - requests=2.32.4=py313hca03da5_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rfc3987-syntax=1.1.0=pyhe01879c_1
  - rich=13.9.4=py313hca03da5_0
  - rpds-py=0.27.1=py313h80e0809_1
  - ruamel.yaml=0.18.10=py313h80987f9_0
  - ruamel.yaml.clib=0.2.12=py313h80987f9_0
  - semver=3.0.2=py313hca03da5_1
  - send2trash=1.8.3=pyh31c8845_1
  - setuptools=72.1.0=py313hca03da5_0
  - shellingham=1.5.0=py313hca03da5_0
  - simdjson=3.10.1=h48ca7d4_0
  - six=1.17.0=pyhe01879c_1
  - sniffio=1.3.1=pyhd8ed1ab_1
  - soupsieve=2.8=pyhd8ed1ab_0
  - spdlog=1.11.0=h48ca7d4_0
  - sqlite=3.50.2=h79febb2_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - terminado=0.18.1=pyh31c8845_0
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.15=hcd8a7d5_0
  - tomli=2.2.1=py313hca03da5_0
  - tornado=6.5.2=py313hcdf3177_1
  - tqdm=4.67.1=py313h7eb115d_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - truststore=0.10.1=py313hca03da5_0
  - typer=0.9.0=py313hca03da5_0
  - types-python-dateutil=2.9.0.20250822=pyhd8ed1ab_0
  - typing-extensions=4.12.2=py313hca03da5_0
  - typing-inspection=0.4.0=py313hca03da5_0
  - typing_extensions=4.12.2=py313hca03da5_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - uri-template=1.3.0=pyhd8ed1ab_1
  - urllib3=2.5.0=py313hca03da5_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - webcolors=24.11.1=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.8.0=pyhd8ed1ab_1
  - wheel=0.45.1=py313hca03da5_0
  - xz=5.6.4=h80987f9_1
  - yaml=0.2.5=h925e9cb_3
  - yaml-cpp=0.8.0=h313beb8_1
  - zeromq=4.3.5=h888dc83_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.2.13=h18a0788_1
  - zstandard=0.23.0=py313h1a4646a_1
  - zstd=1.5.6=hfb09047_0
  - pip:
      - catboost==1.2.8
      - contourpy==1.3.3
      - cramjam==2.11.0
      - cycler==0.12.1
      - duckdb==1.4.3
      - fastparquet==2024.11.0
      - fonttools==4.60.1
      - fsspec==2025.12.0
      - graphviz==0.21
      - imageio==2.37.0
      - joblib==1.5.2
      - kagglehub==0.3.13
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - matplotlib==3.10.7
      - narwhals==2.13.0
      - networkx==3.5
      - pandas==2.3.3
      - pillow==12.0.0
      - plotly==6.5.0
      - pyarrow==22.0.0
      - pyparsing==3.2.5
      - scikit-image==0.25.2
      - scikit-learn==1.8.0
      - scipy==1.16.2
      - seaborn==0.13.2
      - threadpoolctl==3.6.0
      - tifffile==2025.10.16
      - tzdata==2025.3
prefix: /opt/miniconda3
